### ISSUE TITLE
Crash script

### ISSUE THREAD

**Issue by Gandarskog** [talymo/instaAutomate#3]
![Crash](https://user-images.githubusercontent.com/47420130/52420934-569c1580-2af3-11e9-9bd8-e570866f5e00.png)  

When i click --- continue script ---
i get this
![crash2](https://user-images.githubusercontent.com/47420130/52421509-7a139000-2af4-11e9-8b6d-c758804583d2.png)

After that i again get first crash.

**Comment by talymo** [comment]
I haven't updated this code, so if AutoHotkey or the Instagram site has changed anything, this will need updating. There isn't a big enough interest in this for me to keep it updated, so I won't spend time doing it.
